### PR TITLE
Add links to reference implementations

### LINKED ISSUE #7: Include link to reference implementations at beginning of specification
- https://github.com/bigchaindb/pycoalaip
- https://github.com/bigchaindb/pycoalaip-bigchaindb

### PR DESCRIPTION
**Pull request by TimDaub**
Fixes #7

### CODE REVIEW

**Comment by sohkai** [comment]
Not really sure it should be one of the first sections (especially before the whole _read me first_ spiel; I was going to add it to the end sections.

**Comment by TimDaub** [comment]
Fair enough. The document itself should remain a spec.

I propose the following:

We merge this PR (as we currently have some nice traffic and I want people to see that we've started to implement), but actually we want to put the spec's content into it's own clean .md file whilst all meta data around process, organization and references goes into the document people see when they open the repository.
Kinda like here: https://github.com/ipld/specs

OK?

**Comment by sohkai** [comment]
Sounds good, we can transition to the IPFS spec format once this round of edits are done (https://github.com/COALAIP/specs/issues/9).

(Awkward -- it looks like my email reply last week didn't work, maybe related to the outage).

**Comment by sohkai** [comment]
Sounds good.

**Comment by ig-shaun** [comment]
Very happy with that, thanks Tim!

Dr Shaun Conway Founding Director 9Needs - Connected Development M: +27.844099911 S: shaun.conway @9needs
On Thu, Oct 20, 2016 at 10:34 pm, Tim Daubenschütz notifications@github.com wrote:
Fair enough. The document itself should remain a spec.

I propose the following:

We merge this PR (as we currently have some nice traffic and I want people to see that we've started to implement), but actually we want to put the spec's content into it's own clean .md file whilst all meta data around process, organization and references goes into the document people see when they open the repository.
Kinda like here: https://github.com/ipld/specs [https://github.com/ipld/specs]

OK?

**Pull request merged**
